import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  documentationSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Documentation Home'
    },
    {
      type: 'category',
      label: 'Tutorials',
      description: 'Learning-oriented guides for getting started',
      items: [
        {
          type: 'autogenerated',
          dirName: 'tutorials',
        },
      ],
    },
    {
      type: 'category',
      label: 'How-to Guides',
      description: 'Problem-oriented solutions for specific tasks',
      items: [
        {
          type: 'autogenerated',
          dirName: 'how-to-guides',
        },
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      description: 'Information-oriented technical specifications',
      items: [
        'reference/index',
        {
          type: 'category',
          label: 'API Documentation',
          items: [
            {
              type: 'autogenerated',
              dirName: 'reference/api',
            },
          ],
        },
        {
          type: 'category',
          label: 'Schema Reference',
          items: [
            {
              type: 'autogenerated',
              dirName: 'reference/schemas',
            },
          ],
        },
        'reference/errors',
        'reference/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Explanation',
      description: 'Understanding-oriented context and design rationale',
      items: [
        {
          type: 'autogenerated',
          dirName: 'explanation',
        },
      ],
    },
  ],
};

export default sidebars;
