import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  schemasSidebar: [
    'index',
    'attack-ids',
    'common-properties',
    'relationship-types',
    'stix-bundle.schema',
    {
      type: 'category',
      label: 'STIX Domain Objects',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sdo',
        },
      ],
    },
    {
      type: 'category',
      label: 'STIX Relationship Objects',
      items: [
        {
          type: 'autogenerated',
          dirName: 'sro',
        },
      ],
    },
    {
      type: 'category',
      label: 'STIX Meta Objects',
      items: [
        {
          type: 'autogenerated',
          dirName: 'smo',
        },
      ],
    },
    'changelog-schema',
  ],
};

export default sidebars;