import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  schemasSidebar: [
    {
      type: 'category',
      label: 'Schema Reference',
      link: { type: 'doc', id: 'index' },
      items: [
        'stix-bundle.schema',
        {
          type: 'category',
          label: 'STIX Domain Objects',
          items: [
            {
              type: 'autogenerated',
              dirName: 'sdo',
            },
          ],
        },
        {
          type: 'category',
          label: 'STIX Relationship Objects',
          items: [
            {
              type: 'autogenerated',
              dirName: 'sro',
            },
          ],
        },
        {
          type: 'category',
          label: 'STIX Meta Objects',
          items: [
            {
              type: 'autogenerated',
              dirName: 'smo',
            },
          ],
        },
      ],
    },
  ],
};

export default sidebars;