import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  documentationSidebar: [
    {
      type: 'doc',
      id: 'index',
      label: 'Documentation Home',
    },
    {
      type: 'doc',
      id: 'overview',
    },
    {
      type: 'category',
      label: 'Tutorials',
      description: 'Learning-oriented guides for getting started',
      link: { type: 'doc', id: 'tutorials/index' },
      items: [
        'tutorials/your-first-query',
        'tutorials/technique-browser',
        'tutorials/relationships',
        'tutorials/multi-domain-analysis',
      ],
    },
    {
      type: 'category',
      label: 'How-to Guides',
      description: 'Problem-oriented solutions for specific tasks',
      link: { type: 'doc', id: 'how-to-guides/index' },
      items: [
        'how-to-guides/manage-data-sources',
        'how-to-guides/validate-bundles',
        'how-to-guides/error-handling',
        'how-to-guides/performance',
      ],
    },
    {
      type: 'category',
      label: 'Reference',
      description: 'Information-oriented technical specifications',
      link: { type: 'doc', id: 'reference/index' },
      items: [
        {
          type: 'category',
          label: 'API Documentation',
          link: { type: 'doc', id: 'reference/api/index' },
          items: [
            'reference/api/data-sources',
            'reference/api/attack-data-model',
            'reference/api/utilities',
          ],
        },
        {
          type: 'category',
          label: 'Schema Reference',
          link: { type: 'doc', id: 'reference/schemas/index' },
          items: [
            'reference/schemas/stix-bundle.schema',
            {
              type: 'category',
              label: 'STIX Domain Objects',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'reference/schemas/sdo',
                },
              ],
            },
            {
              type: 'category',
              label: 'STIX Relationship Objects',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'reference/schemas/sro',
                },
              ],
            },
            {
              type: 'category',
              label: 'STIX Meta Objects',
              items: [
                {
                  type: 'autogenerated',
                  dirName: 'reference/schemas/smo',
                },
              ],
            },
          ],
        },
        'reference/errors',
        'reference/configuration',
      ],
    },
    {
      type: 'category',
      label: 'Principles',
      description: 'Understanding-oriented context and design rationale',
      link: { type: 'doc', id: 'principles/index' },
      items: [
        'principles/why-adm-exists',
        'principles/why-zod',
        'principles/stix-foundation',
        'principles/attack-specification-overview',
        'principles/versioning-philosophy',
        'principles/schema-design',
        'principles/compatibility',
        'principles/trade-offs',
      ],
    },
    {
      type: 'category',
      label: 'Contributing',
      description: 'How to contribute to the project',
      link: { type: 'doc', id: 'contributing/index' },
      items: [
        'contributing/dev-setup',
        'contributing/coding-style',
        'contributing/tests',
        'contributing/docs',
      ],
    },
  ],
};

export default sidebars;
